---
title: "Available datasets"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

options(DT.warn.size = FALSE)
library(DT)
library(dplyr)

tablify <- function(x, ...) {
  datatable(
    x, 
    style = "bootstrap4",
    rownames = FALSE,
    options = list(
      pageLength = 10,
      lengthMenu = c(10, 100, 500, 1000),
      fixedHeader = TRUE,
      # paging = FALSE,
      autoWidth = TRUE,
      columnDefs = list(
        list(targets = 0, width = '50px'),
        list(targets = 1, width = '60px'),
        list(targets = 3, searchable = FALSE),
        list(targets = 4, width = '200px'),
        list(targets = 5, width = '200px')
      )
    ), 
    filter = "top",
    ...
  )
}

```

This is a slightly adapted version of [Vincent's very handy project](https://github.com/vincentarelbundock/Rdatasets) with some added packages and a couple of tweaks to the table.

```{r, messages=FALSE, warnings=FALSE, echo=FALSE}
xdat <- read.csv(here::here("datasets.csv")) %>%
  mutate(
    Package = factor(Package),
    CSV = paste0('<a href="', CSV, '">CSV</a>'),
    #CSV = purrr::map(CSV, htmltools::HTML),
    Doc = paste0('<a href="', Doc, '">Doc</a>'),
    #Doc = purrr::map(Doc, htmltools::HTML),
    Link = paste(CSV, "<br/>", Doc),
    Link = purrr::map(Link, htmltools::HTML)
  ) %>%
  select(Package, Item, Title, Link, Rows, Cols, order(names(.)), -CSV, -Doc)

tablify(xdat)
```
